version: 0.1

prod:
  deploy:
    parameters:
      stack_name: "cm-landing-secret"
      s3_bucket: "dytms-sam-deployments"
      s3_prefix: "cm-landing-secret"
      region: "us-east-1"
      parameter_overrides:
        - "SecretName=cm-landing-api-secret"
      confirm_changeset: true
      fail_on_empty_changeset: false
