version: 0.1

prod:
  deploy:
    parameters:
      stack_name: "cm-landing-api"
      s3_bucket: "dytms-sam-deployments"
      s3_prefix: "cm-landing-api"
      region: "us-east-1"
      capabilities: "CAPABILITY_IAM"
      parameter_overrides:
        - "Environment=prod"
        - "ApiDomainName=api.landing.credomaxtrans.com"
        - "HostedZoneId=Z00099751WUXT9G3CV8UT"
        - "ConfigSecretName=cm-landing-api-secret"
        - "LambdaExecutionRoleArn=arn:aws:iam::488479523924:role/cm-landing-role-LandingApiLambdaRole-4wo5lW8YTa85"
      confirm_changeset: true
      fail_on_empty_changeset: false
